project_id = "kfwxlqtybutiwftfjuky"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.validate-appointment-date]
verify_jwt = false

[functions.cancel-expired-appointments]
verify_jwt = false