// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfwxlqtybutiwftfjuky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtmd3hscXR5YnV0aXdmdGZqdWt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzOTYyNjcsImV4cCI6MjA2Njk3MjI2N30.IankYuGWAA34xUkuYzo1wyyICy_r8n8IWEGccPSJ114";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});